url: "https://flamegapps.github.io"
description: "A Custom GApps Package For Arm64 Devices"
keywords: flamegapps, flame gapps, gapps, gapps download, download flamegapps, flamegapps download, android 9, android 10

plugins:
  - jekyll-seo-tag
